# Generated by Django 5.0.3 on 2024-03-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('department_name', models.CharField(max_length=255, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('intern_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Intern ID')),
                ('department_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=20)),
                ('intern_status', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('mobile_number', models.CharField(max_length=11)),
                ('school', models.CharField(max_length=255)),
                ('year_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('degree', models.CharField(max_length=255)),
                ('internship_type', models.CharField(choices=[('Voluntary', 'Voluntary'), ('Required', 'Required')], max_length=20)),
                ('school_coordinator', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nda_file', models.CharField(blank=True, max_length=255, null=True)),
                ('min_workload_threshold', models.IntegerField(default=5)),
                ('max_workload_threshold', models.IntegerField(default=100)),
                ('intern_head_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_date_created', models.DateField()),
                ('task_due_date', models.DateField()),
                ('task_estimated_time_to_finish', models.FloatField()),
                ('task_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mid_initial', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('I', 'Intern'), ('DS', 'Department Supervisor')], default='I', max_length=2)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=20, verbose_name='Task Status')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('file_submission', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Submission')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task', verbose_name='Task ID')),
                ('intern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount', verbose_name='Intern User ID')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('dept_acct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.useraccount', verbose_name='Department Supervisor ID')),
            ],
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('concern_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concern_description', models.TextField()),
                ('academic_workload', models.CharField(choices=[('Full Semester', 'Yes (taking full semester)'), ('Few Classes Only', 'Yes (taking few classes only)'), ('No', 'No')], max_length=50)),
                ('other_commitments', models.TextField()),
                ('date_filed', models.DateField()),
                ('intern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount', verbose_name='Intern User ID')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('workload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_date', models.DateField()),
                ('workload_points', models.PositiveSmallIntegerField(default=0)),
                ('workload_tag', models.CharField(choices=[('Underload', 'Underload'), ('Minimum Capacity', 'Minimum Capacity'), ('In Capacity', 'In Capacity'), ('Maximum Capacity', 'Maximum Capacity'), ('Overload', 'Overload')], max_length=20)),
                ('intern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount', verbose_name='Intern User ID')),
            ],
        ),
    ]
