# Generated by Django 5.0.1 on 2024-02-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=20)),
                ('intern_status', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('mobile_number', models.CharField(max_length=11)),
                ('school', models.CharField(max_length=255)),
                ('year_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('degree', models.CharField(max_length=255)),
                ('internship_type', models.CharField(choices=[('Voluntary', 'Voluntary'), ('Required', 'Required')], max_length=20)),
                ('school_coordinator', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nda_file', models.CharField(blank=True, max_length=255, null=True)),
                ('min_workload_threshold', models.IntegerField()),
                ('max_workload_threshold', models.IntegerField()),
                ('intern_head_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(default=9999, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=20)),
                ('task_file_submission', models.CharField(blank=True, max_length=255, null=True)),
                ('task_date_created', models.DateField()),
                ('task_due_date', models.DateField()),
                ('task_estimated_time_to_finish', models.FloatField()),
                ('task_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=255)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_middle_initial', models.CharField(max_length=255)),
                ('user_account_type', models.CharField(choices=[('I', 'Intern'), ('DS', 'Department Supervisor')], default='I', max_length=2)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
