# Generated by Django 3.2.10 on 2024-05-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='required_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='intern_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount'),
        ),
    ]
