# Generated by Django 3.2.10 on 2024-05-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240502_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('subtask_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtask_description', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
    ]
