# Generated by Django 5.0.1 on 2024-02-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_intern_task_useraccount_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='intern',
            name='intern_id',
            field=models.BigAutoField(default=9999, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_id',
            field=models.BigAutoField(default=9999, primary_key=True, serialize=False),
        ),
    ]
