# Generated by Django 5.0.1 on 2024-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_account_type_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('department_name', models.CharField(max_length=255, verbose_name='Department Name')),
            ],
        ),
        migrations.AlterField(
            model_name='intern',
            name='intern_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intern',
            name='max_workload_threshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='min_workload_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
