# Generated by Django 5.0.1 on 2024-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_departmentsupervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('concern_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intern_id', models.IntegerField()),
                ('concern_description', models.TextField()),
                ('academic_workload', models.CharField(choices=[('Full Semester', 'Yes (taking full semester)'), ('Few Classes Only', 'Yes (taking few classes only)'), ('No', 'No')], max_length=50)),
                ('other_commitments', models.TextField()),
                ('date_filed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('task_assignment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Task Assignment ID')),
                ('intern_id', models.IntegerField(verbose_name='Intern User ID')),
                ('task_id', models.IntegerField(verbose_name='Task ID')),
                ('task_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=20, verbose_name='Task Status')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('file_submission', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('workload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intern_id', models.IntegerField()),
                ('week_date', models.DateField()),
                ('workload_points', models.PositiveSmallIntegerField(default=0)),
                ('workload_tag', models.CharField(choices=[('Underload', 'Underload'), ('Minimum Capacity', 'Minimum Capacity'), ('In Capacity', 'In Capacity'), ('Maximum Capacity', 'Maximum Capacity'), ('Overload', 'Overload')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_file_submission',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
    ]
