# Generated by Django 5.0.3 on 2024-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='intern_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
